const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../public'),out=path.resolve(__dirname,'../validation/v2-screenshots');fs.mkdirSync(out,{recursive:true});const checks=[],errors=[];
const check=(label,ok)=>{assert.ok(ok,label);checks.push(label);console.log('PASS '+label);};
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.json')?'application/json':file.endsWith('.glb')?'model/gltf-binary':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('404');}});
(async()=>{await new Promise(r=>server.listen(3022,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1536,height:1040}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const snap=()=>page.evaluate(()=>window.flightSnapshot());
const choose=async(name,id)=>{await page.fill('#destination-search',name);await page.click('[data-id="'+id+'"]');};
const fly=async()=>{await page.click('#engage');await page.selectOption('#time-rate','10000');await page.waitForFunction(()=>window.flightSnapshot().closeup,{},{timeout:90000});check('Visible final approach entered',!(await snap()).paused);await page.screenshot({path:out+'/nav-approach.png'});await page.waitForFunction(()=>!!window.flightSnapshot().arrival,{},{timeout:120000});await page.waitForFunction(()=>window.flightSnapshot().marker&&!window.flightSnapshot().marker.offscreen);};
try{
page.setDefaultTimeout(60000);await page.goto('http://127.0.0.1:3022/cockpit.html');await page.waitForFunction(()=>typeof window.flightSnapshot==='function');
if(!process.argv.includes('--remaining')&&!process.argv.includes('--final')&&!process.argv.includes('--smoke')){await choose('Terre','solar:Terre');await page.click('#engage');await page.selectOption('#time-rate','10000');await page.waitForFunction(()=>window.flightSnapshot().closeup);await page.selectOption('#time-rate','10000');await page.waitForFunction(()=>!!window.flightSnapshot().arrival);await page.waitForFunction(()=>window.flightSnapshot().closeupModel.ready);await page.waitForFunction(()=>window.flightSnapshot().navCompact,{},{timeout:60000});check('Real Earth arrival auto-collapses panel',(await snap()).arrival.id==='solar:Terre');await page.click('#navigation-toggle');check('Arrival details can be reopened',!(await snap()).navCompact);await page.click('#navigation-toggle');
await page.click('#approach');await page.selectOption('#time-rate','10000');await page.waitForFunction(()=>!!window.flightSnapshot().arrival);await page.click('#clean-view');await page.screenshot({path:out+'/visual-earth.png'});check('Clean view hides overlays and preserves 3D',await page.locator('#restore-view').isVisible()&&!(await page.locator('#navigation-hud').isVisible()));await page.click('#restore-view');}
await page.locator('#wormhole-enabled').check();
const visits=[['Mercure','solar:Mercure','mercury'],['Vénus','solar:Vénus','venus'],['Lune','moon:Lune','moon'],['Mars','solar:Mars','mars'],['Jupiter','solar:Jupiter','jupiter'],['Saturne','solar:Saturne','saturn'],['Uranus','solar:Uranus','uranus'],['Neptune','solar:Neptune','neptune'],['Proxima Cen b','planet:Proxima Cen b','exoplanet'],['Proxima Centauri','h70666','star'],['Vela','vela','pulsar'],['SGR J1745','magnetar-gc','magnetar'],['M13','globular:NGC6205','cluster'],['Piliers','pillars','pillars'],['Orion','orion','orion'],['Gaia BH1','gaia-bh1','blackhole-dark'],['Sagittarius A','sgr-a','blackhole-disk']];
for(const [name,id,label] of visits){if(process.argv.includes('--smoke')&&!['cluster','blackhole-disk'].includes(label))continue;if(process.argv.includes('--final')&&!['saturn','magnetar','pillars','cluster'].includes(label))continue;if(process.argv.includes('--remaining')&&!['saturn','magnetar','pillars','orion','blackhole-dark','blackhole-disk'].includes(label))continue;await choose(name,id);await page.click('#wormhole-jump');await page.waitForFunction(()=>!window.flightSnapshot().passage);await page.waitForFunction(id=>window.flightSnapshot().localId===id,id,{timeout:45000});if(!['cluster','pillars','orion','blackhole-dark','blackhole-disk'].includes(label))await page.waitForFunction(()=>window.flightSnapshot().closeupModel.ready,{},{timeout:45000});await page.click('#clean-view');await page.screenshot({path:out+'/visual-'+label+'.png'});check('Visit rendered '+label,errors.length===0);await page.click('#restore-view');}
await choose('Terre','solar:Terre');await page.click('#wormhole-jump');await page.waitForFunction(()=>!window.flightSnapshot().passage);await page.click('#external-view');await page.screenshot({path:out+'/visual-external.png'});await page.click('#cockpit-view');await page.click('#compare-physics');await page.screenshot({path:out+'/visual-relativity.png'});check('Relativistic comparison remains functional',(await snap()).opticalLab);await page.click('#close-lab');await page.setViewportSize({width:390,height:844});await page.click('#clean-view');await page.screenshot({path:out+'/visual-mobile.png'});check('Mobile clean view has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('All maps loaded without error',(await snap()).closeupModel.errors.length===0);check('No browser or shader errors',errors.length===0);
}catch(e){errors.push(e.message);await page.screenshot({path:out+'/nav-failure.png',fullPage:true});throw e;}finally{fs.writeFileSync(out+(process.argv.includes('--smoke')?'/visual-smoke-results.json':process.argv.includes('--final')?'/visual-final-results.json':process.argv.includes('--remaining')?'/visual-remaining-results.json':'/visual-results.json'),JSON.stringify({checks,errors},null,2));await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
