const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../public'),out=path.resolve(__dirname,'../validation/v2-screenshots'),checks=[],errors=[];
const check=(label,ok)=>{assert.ok(ok,label);checks.push(label);console.log('PASS '+label);fs.writeFileSync(out+'/v2-results.json',JSON.stringify({checks,errors},null,2));};
const server=http.createServer((req,res)=>{let file=path.join(root,decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.json')?'application/json':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('404');}});
(async()=>{await new Promise(r=>server.listen(3017,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1536,height:1040}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const snap=()=>page.evaluate(()=>window.flightSnapshot());
try{
 await page.goto('http://127.0.0.1:3017/cockpit.html');await page.waitForFunction(()=>typeof window.flightSnapshot==='function');await page.waitForFunction(()=>window.flightSnapshot().voyagerReady);
 check('Default cockpit relativistic, uncapped and separate craft',(await snap()).relativistic&&(await snap()).cap===1&&(await snap()).shipName==='Odyssée-01');
 await page.fill('#destination-search','Gaia BH1');await page.click('[data-id="gaia-bh1"]');await page.locator('#wormhole-enabled').check();await page.click('#wormhole-jump');await page.waitForFunction(()=>window.flightSnapshot().lensActive);await page.screenshot({path:out+'/v2-bh-fixed.png'});check('Schwarzschild lens and all-sky optical pass run',(await snap()).lensActive);
 await page.fill('#destination-search','Voyager');await page.click('[data-id="voyager-1"]');await page.click('#wormhole-jump');await page.waitForFunction(()=>window.flightSnapshot().local);await page.screenshot({path:out+'/voyager-visited.png'});check('Voyager visit independent of Odyssee',(await snap()).localId==='voyager-1');
 await page.click('#home');await page.click('.hazards summary');await page.locator('#fictional-shield').uncheck();await page.selectOption('#gas-density','100');await page.selectOption('#time-rate','100');await page.click('#thrust');await page.waitForFunction(()=>window.flightSnapshot().paused);check('Hazard threshold pauses with shield off',(await snap()).risk.gasPower>1e6);await page.locator('#fictional-shield').check();await page.click('#home');await page.click('.hazards summary');
 await page.click('#clear-target');await page.selectOption('#time-rate','10000');await page.click('#thrust');await page.waitForFunction(()=>window.flightSnapshot().gamma>1000);await page.click('#pause');const fast=await snap();check('High gamma finite and below c represented',fast.gamma>1000&&fast.betaGap>0&&Number.isFinite(fast.tau));await page.screenshot({path:out+'/uncapped-flight.png'});await page.locator('#speed-limiter').check();check('Limiter engages brake without velocity discontinuity',(await snap()).engine==='brake');await page.locator('#speed-limiter').uncheck();await page.click('#home');
 await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:3017/cockpit.html');await page.waitForFunction(()=>typeof window.flightSnapshot==='function');check('Mobile no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.click('#hide-nav');await page.fill('#destination-search','Lune');await page.click('[data-id="moon:Lune"]');await page.locator('#wormhole-enabled').check();await page.click('#wormhole-jump');await page.waitForFunction(()=>window.flightSnapshot().local);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:out+'/cockpit-mobile.png',fullPage:true});check('Mobile destination and local rendering',(await snap()).localId==='moon:Lune');await page.click('#map-view');check('Mobile galactic map works',(await snap()).map);
 await page.goto('http://127.0.0.1:3017/physics-v2.html');check('Version guide renders trip table',await page.locator('#trips tr').count()===4);check('No WebGL, shader or browser errors',errors.length===0);
}catch(e){await page.screenshot({path:out+'/v2-failure.png',fullPage:true});console.log('ERRORS',errors);throw e;}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
