import {AU,LY,add,mul,norm} from './physics.js';
export function hash(s){let h=2166136261;for(let c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0;}
export function catalogObjects(stars){let out=[...stars];for(let s of stars){for(let p of s.planets||[]){const radius=p.radiusEarth?6371*p.radiusEarth:6371;let a=(hash(p.name)%62832)/10000;let offset=p.axisAU?mul([Math.cos(a),Math.sin(a),.03*Math.sin(a*2)],p.axisAU*AU):[0,0,0];out.push({id:'planet:'+p.name,name:p.name,type:'planet',parent:s.id,host:s.name,xyz:add(s.xyz,offset),d:norm(add(s.xyz,offset)),radiusKm:radius,radiusAssumed:!p.radiusEarth,planet:p,guide:s.guide||['Kepler-22','Kepler-186','Kepler-452','Kepler-1708'].includes(s.host),aliases:[],planets:[],kind:p.radiusEarth>4?'Géante gazeuse':'Exoplanète',note:'Planète répertoriée par la NASA. Surface, nuages et phase orbitale sont illustratifs ; ils ne sont pas observés dans cette simulation.',links:[['NASA · fiche de la planète','https://exoplanetarchive.ipac.caltech.edu/overview/'+encodeURIComponent(p.name)]]});}}
const solar=[['Mercure',.387,2440,'rock'],['Vénus',.723,6052,'venus'],['Terre',1,6371,'earth'],['Mars',1.524,3390,'mars'],['Jupiter',5.203,69911,'gas'],['Saturne',9.537,58232,'saturn'],['Uranus',19.2,25362,'ice'],['Neptune',30.07,24622,'ice']];let parents={};
for(let [i,[name,a,r,skin]] of solar.entries()){const angle=i*.75;let o={id:'solar:'+name,name,type:'planet',skin,parent:'h0',host:'Soleil',xyz:mul([Math.cos(angle),Math.sin(angle)*.9175,Math.sin(angle)*.3978],a*AU),radiusKm:r,aliases:[],guide:true,planets:[],kind:'Planète du Système solaire',note:'Position calculée à la date de mission avec les éléments approchés du JPL (Standish) ; orientation selon les éléments de rotation IAU. Les textures sont des cartes de surface, pas une observation du jour. Voir le statut de l’éphéméride ci-dessous.',links:[['NASA · Système solaire','https://science.nasa.gov/solar-system/']]};o.d=norm(o.xyz);parents[name]=o;out.push(o);}
for(let [name,parent,r,axis] of [['Lune','Terre',1737.4,384400],['Europe','Jupiter',1560.8,671100],['Io','Jupiter',1821.6,421700],['Ganymède','Jupiter',2634.1,1070400],['Titan','Saturne',2574.7,1221870],['Encelade','Saturne',252.1,238000],['Triton','Neptune',1353.4,354759]]){let p=parents[parent];out.push({id:'moon:'+name,name,type:'moon',skin:name==='Titan'?'venus':'moon',parent:p.id,host:parent,xyz:add(p.xyz,[axis*1000/LY,0,0]),d:p.d,radiusKm:r,aliases:[],planets:[],guide:true,kind:'Lune · '+parent,note:name==='Lune'?'Position calculée à la date de mission par une théorie lunaire simplifiée (quelques minutes d’arc) ; face visible tournée vers la Terre (rotation synchrone moyenne).':'Satellite naturel confirmé du Système solaire. Orbite dans le plan équatorial de sa planète avec la période calculée ; la phase sur l’orbite est illustrative, ce n’est pas une éphéméride.',links:[['NASA · lunes','https://science.nasa.gov/solar-system/moons/']]});}
return out;}
export function radiusLy(o){return o.radiusLy||(o.radiusKm||((o.radiusSolar||1)*695700))*1000/LY;}
export function standOff(o){return radiusLy(o)*(o.type==='blackhole'?15:o.type==='nebula'||o.type==='pillars'||o.type==='galaxy'||o.type==='cosmic'?2.4:5);}
