import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {CosmicScene} from './cosmic-scene.js';
import {STRUCTURES,LEVELS,TYPE_NAMES,xyz} from './cosmic-data.js';
const $=id=>document.getElementById(id),fmt=(n,p=1)=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:p}).format(n),byId=new Map(STRUCTURES.map(o=>[o.id,o]));
window.addEventListener('error',e=>{$('loading').hidden=true;$('error').hidden=false;$('error').textContent='Le rendu 3D a rencontré une erreur. Recharge la page ou vérifie que WebGL est disponible.';});
const canvas=$('cosmos'),renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x03080f);renderer.outputColorSpace=T.SRGBColorSpace;const scene=new T.Scene(),camera=new T.PerspectiveCamera(48,1,.00001,10000);camera.up.set(0,0,1);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=.005;controls.maxDistance=5000;const cosmic=new CosmicScene();scene.add(cosmic.root);
let level=0,selected='local-group',span=8,transition=null,immersion=false,last=0,keys=new Set(),down=null,drag=false;
const labelNodes=new Map(),leaderNodes=new Map();for(const o of STRUCTURES){const b=document.createElement('button');b.className='label';b.textContent=o.name;b.onclick=()=>select(o.id,true);const line=document.createElement('i');line.className='label-leader';$('labels').append(line,b);labelNodes.set(o.id,b);leaderNodes.set(o.id,line);}
$('levels').innerHTML=LEVELS.map((l,i)=>`<button data-level="${i}">${i+1} · ${l.name}</button>`).join('');$('levels').onclick=e=>{const b=e.target.closest('[data-level]');if(b)setLevel(+b.dataset.level);};
$('address').innerHTML=['milky-way','local-group','virgo-supercluster','laniakea'].map(id=>`<button data-object="${id}">${byId.get(id).name}</button>`).join('');$('address').onclick=e=>{const b=e.target.closest('[data-object]');if(b)select(b.dataset.object,true);};
function results(){const q=$('search').value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const rows=STRUCTURES.filter(o=>!q||[o.name,o.id,TYPE_NAMES[o.type]].join(' ').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(q));$('results').innerHTML=rows.map(o=>`<button data-object="${o.id}" class="${selected===o.id?'active':''}">${o.name}</button>`).join('')||'<small>Aucune structure trouvée.</small>';}
$('search').oninput=results;$('results').onclick=e=>{const b=e.target.closest('[data-object]');if(b)select(b.dataset.object,true);};
function details(){const o=byId.get(selected);$('kind').textContent=TYPE_NAMES[o.type];$('name').textContent=o.name;$('summary').textContent=o.summary;$('relation').textContent=o.relation;$('distance').textContent=(o.id==='local-group'?'Nous sommes dans ce groupe':o.type==='basin'||o.type==='supercluster'||o.type==='attractor'?'Repère de cadrage : ≈ '+fmt(o.d)+' millions d’al':'Centre : ≈ '+fmt(o.d,o.d<1?3:1)+' millions d’al');$('coordinates').textContent=`Direction équatoriale J2000 : α ${fmt(o.ra,2)}°, δ ${fmt(o.dec,2)}°. X ${fmt(o.p[0])}, Y ${fmt(o.p[1])}, Z ${fmt(o.p[2])} millions d’al depuis le Soleil. Coordonnées arrondies / point de cadrage pour les régions étendues.`;$('extent').textContent=o.extent;$('sources').innerHTML=o.links.map(([name,url])=>`<a href="${url}" target="_blank" rel="noopener">${name}</a>`).join('');$('relations').innerHTML=[['Inclus dans',o.inside],['À explorer dans cet ensemble',o.contains]].map(([title,ids])=>ids.length?`<div class="related"><small>${title}</small>${ids.map(id=>`<button data-object="${id}">${byId.get(id).name}</button>`).join('')}</div>`:'').join('');$('enter').textContent=o.type==='void'?'Entrer dans le vide':'Explorer l’intérieur';$('flight').href='./cockpit.html?target='+encodeURIComponent(['m31','m33'].includes(o.id)?o.id:o.id==='milky-way'?'sgr-a':'cosmic:'+o.id);results();}
$('relations').onclick=e=>{const b=e.target.closest('[data-object]');if(b)select(b.dataset.object,true);};
function leaveImmersion(){immersion=false;keys.clear();controls.enabled=true;document.body.classList.remove('immersion');$('touch-controls').hidden=true;}
function frame(center,r,instant=false){leaveImmersion();const end=new T.Vector3(...center),offset=new T.Vector3(1,-1.45,.9).normalize().multiplyScalar(r*1.35);span=r;transition={from:camera.position.clone(),fromTarget:controls.target.clone(),to:end.clone().add(offset),target:end,time:performance.now(),duration:instant?0:1100};}
function setLevel(i,instant=false){level=Math.max(0,Math.min(LEVELS.length-1,i));const l=LEVELS[level];selected=l.focus;const center=level===3?[0,0,0]:byId.get(l.focus).p;frame(center,l.span,instant);ui();}
function select(id,focus=false){if(!byId.has(id))return;selected=id;level=Math.max(level,byId.get(id).level);if(focus)frame(byId.get(id).p,Math.max(byId.get(id).r*3.1,.2));ui();}
function ui(){const l=LEVELS[level];$('level-title').textContent=l.name;$('level-caption').textContent=l.text;$('previous').disabled=level===0;$('next').disabled=level===LEVELS.length-1;document.querySelectorAll('[data-level]').forEach(b=>b.classList.toggle('active',+b.dataset.level===level));details();}
$('previous').onclick=()=>setLevel(level-1);$('next').onclick=()=>setLevel(level+1);$('home').onclick=()=>setLevel(0);$('focus').onclick=()=>select(selected,true);$('outside').onclick=()=>frame(byId.get(selected).p,Math.max(byId.get(selected).r*3.1,.2));
$('enter').onclick=()=>{const o=byId.get(selected);transition=null;controls.enabled=false;immersion=true;keys.clear();document.body.classList.add('immersion');$('touch-controls').hidden=false;span=Math.max(o.r*.8,.1);const center=new T.Vector3(...o.p);camera.position.copy(center).add(new T.Vector3(.2,-.3,.13).multiplyScalar(o.r));camera.lookAt(center);canvas.focus();};
$('clean').onclick=()=>{document.body.classList.add('clean');$('restore').hidden=false;resize();};$('restore').onclick=()=>{document.body.classList.remove('clean');$('restore').hidden=true;resize();};
function resize(){const r=canvas.parentElement.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas.parentElement);resize();
canvas.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];drag=false;if(immersion)canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!down)return;const dx=e.clientX-down[0],dy=e.clientY-down[1];if(Math.hypot(dx,dy)>3)drag=true;if(immersion){camera.rotateOnWorldAxis(new T.Vector3(0,0,1),-dx*.003);camera.rotateX(-dy*.003);down=[e.clientX,e.clientY];}});canvas.addEventListener('pointerup',e=>{if(down&&!drag&&!immersion){const r=canvas.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hits=ray.intersectObjects(cosmic.targets).filter(h=>h.object.visible).sort((a,b)=>a.object.userData.data.r-b.object.userData.data.r);if(hits.length)select(hits[0].object.userData.data.id);}down=null;});canvas.addEventListener('pointercancel',()=>down=null);
window.addEventListener('keydown',e=>{if(!immersion||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;keys.add(e.key.toLowerCase());if(['w','z','s','a','q','d','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase()))e.preventDefault();});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());
const moveKeys={forward:'w',back:'s',left:'a',right:'d'};document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();keys.add(moveKeys[b.dataset.move]);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>keys.delete(moveKeys[b.dataset.move]);});
function labels(){const r=canvas.getBoundingClientRect(),occupied=[];const ranked=STRUCTURES.filter(o=>o.id!==selected).sort((a,b)=>((b.type==='attractor'?5:b.level)-(a.type==='attractor'?5:a.level)));const ordered=[byId.get(selected),...ranked];for(const o of ordered){const el=labelNodes.get(o.id),leader=leaderNodes.get(o.id),e=cosmic.entries.find(e=>e.o===o);el.hidden=leader.hidden=true;if(immersion&&o.id!==selected||!e.pick.visible||level>0&&o.type==='galaxy'&&o.id!==selected)continue;const p=new T.Vector3(...o.p).project(camera);if(p.z< -1||p.z>1||Math.abs(p.x)>1||Math.abs(p.y)>1)continue;const px=(p.x+1)*r.width/2,py=(1-p.y)*r.height/2,w=Math.min(r.width<500?165:220,o.name.length*7+18),h=26;let slot;for(const dy of [0,32,-32,64,-64,96,-96]){for(const dx of [10,-w-10]){const x=px+dx,y=py+dy;if(x<5||x+w>r.width-5||y<225||y>r.height-160)continue;if(!occupied.some(a=>x<a.x+a.w&&x+w>a.x&&y<a.y+a.h+5&&y+h+5>a.y)){slot={x,y,w,h};break;}}if(slot)break;}if(!slot)continue;el.hidden=false;el.style.left=slot.x+'px';el.style.top=slot.y+'px';el.classList.toggle('selected',o.id===selected);occupied.push(slot);const tx=slot.x>px?slot.x:slot.x+w,ty=slot.y+h/2;leader.hidden=false;leader.style.left=px+'px';leader.style.top=py+'px';leader.style.width=Math.hypot(tx-px,ty-py)+'px';leader.style.transform='rotate('+Math.atan2(ty-py,tx-px)+'rad)';}}

function animate(now){requestAnimationFrame(animate);const dt=Math.min(.1,(now-last)/1000||0);last=now;if(transition){let f=transition.duration?Math.min(1,(now-transition.time)/transition.duration):1;f=f*f*(3-2*f);camera.position.lerpVectors(transition.from,transition.to,f);controls.target.lerpVectors(transition.fromTarget,transition.target,f);if(f>=1)transition=null;}if(immersion){const speed=span*.25*dt;let z=+([...keys].some(k=>['w','z','arrowup'].includes(k)))-+([...keys].some(k=>['s','arrowdown'].includes(k))),x=+(keys.has('d')||keys.has('arrowright'))-+(keys.has('a')||keys.has('q')||keys.has('arrowleft'));camera.translateZ(-z*speed);camera.translateX(x*speed);}else controls.update();const distance=immersion?span:camera.position.distanceTo(controls.target),width=2*distance*Math.tan(camera.fov*Math.PI/360)*camera.aspect;cosmic.update(level,selected,width,{envelopes:$('envelopes').checked&&!immersion,filaments:$('filaments').checked&&!immersion,boost:Number($('boost').value)});cosmic.material.uniforms.screenHeight.value=canvas.clientHeight;renderer.render(scene,camera);labels();$('scale-readout').textContent=immersion?'IMMERSION · déplacement libre de la caméra':'LARGEUR AU PLAN DE VISÉE · '+fmt(width)+' millions d’al';$('camera-readout').textContent='Caméra à '+fmt(camera.position.length())+' millions d’al du Soleil';$('view-note').textContent=immersion?'Galaxies synthétiques · caméra libre, sans temps de voyage':'Enveloppes et connexions illustratives · distances arrondies';$('ruler').textContent=fmt(width*100/canvas.clientWidth,width<1?3:1)+' millions d’al';}
const query=new URLSearchParams(location.search);setLevel(Math.min(3,Math.max(0,Number(query.get('level'))||0)),true);if(byId.has(query.get('target')))select(query.get('target'),true);$('loading').hidden=true;requestAnimationFrame(animate);
Object.defineProperty(window,'cosmicSnapshot',{value:()=>({level,selected,immersion,camera:camera.position.toArray(),target:controls.target.toArray(),structures:STRUCTURES.length,visible:cosmic.entries.filter(e=>e.mesh.visible).map(e=>e.o.id),boost:cosmic.material.uniforms.boost.value,geometry:'instanced 3D ellipsoids with procedural shading',pixels:renderer.getDrawingBufferSize(new T.Vector2()).toArray()})});
