import * as T from 'three';
import {STRUCTURES} from './cosmic-data.js';
const colors={galaxy:0xf1d2a2,group:0x91dbc8,'galaxy-cluster':0xffc77d,supercluster:0x84b9e9,basin:0x72d7c6,attractor:0xffa56c,void:0xa898ec};
const vs=`varying vec3 p;varying vec3 col;varying vec3 n;uniform float boost,optics,minPixel,screenHeight;uniform vec3 momentum;varying float doppler;void main(){p=position;col=instanceColor;n=normal;vec4 center=modelViewMatrix*instanceMatrix*vec4(0.,0.,0.,1.);float size=length((modelMatrix*vec4(instanceMatrix[0].xyz,0.)).xyz);float floorSize=abs(center.z)*.89/max(screenHeight,1.)*minPixel;float scale=max(boost,floorSize/max(size,1.e-12));vec4 q=instanceMatrix*vec4(position*scale,1.);vec4 world=modelMatrix*q;float d=max(length(world.xyz),1.e-10),u=length(momentum),g=sqrt(1.+u*u);doppler=1.;if(optics>.5&&u>1.e-6){vec3 n=world.xyz/d,e=momentum/u;float mu=dot(n,e);doppler=max(1.e-8,g+u*mu);world.xyz=(n+e*((g-1.)*mu+u))/doppler*d;}gl_Position=projectionMatrix*viewMatrix*world;}`;
const fs=`precision highp float;varying vec3 p,col,n;varying float doppler;void main(){float r=length(p.xy);float elliptical=step(1.1,col.r);float spiral=(1.-elliptical)*pow(.5+.5*cos(2.*atan(p.y,p.x)-7.*log(max(r,.035))),3.);float core=exp(-r*12.);float grain=.65+.35*sin(p.x*9.+sin(p.y*5.))*sin(p.y*7.);float glow=exp(-r*2.5)*(.46+.32*spiral+.22*grain)+core*.9;float edge=1.-smoothstep(.72,1.,r);gl_FragColor=vec4(mix(min(col,vec3(1.)),vec3(1.,.93,.8),core)*glow*clamp(pow(doppler,.6),.03,8.),edge*.86);}`;
const hash=s=>[...s].reduce((n,c)=>(Math.imul(n,31)+c.charCodeAt(0))>>>0,7219);
export class CosmicScene{
 constructor({map=true}={}){this.root=new T.Group();this.map=map;this.entries=[];this.targets=[];this.envelopes=new T.Group();this.filaments=new T.Group();this.galaxies=new T.Group();this.root.add(this.filaments,this.galaxies,this.envelopes);this.byId=new Map(STRUCTURES.map(o=>[o.id,o]));
 const geometry=new T.SphereGeometry(1,32,20);this.material=new T.ShaderMaterial({uniforms:{boost:{value:map?6:1},minPixel:{value:map?1.8:0},screenHeight:{value:1000},optics:{value:0},momentum:{value:new T.Vector3()}},vertexShader:vs,fragmentShader:fs,transparent:true,depthWrite:false,blending:T.AdditiveBlending});
 for(const o of STRUCTURES){let seed=hash(o.id);const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};const normal=()=>Math.sqrt(-2*Math.log(Math.max(rand(),1e-8)))*Math.cos(2*Math.PI*rand());
 const count=o.type==='galaxy'?1:o.type==='void'?12:o.type==='galaxy-cluster'?220:o.type==='group'?70:360;
 const mesh=new T.InstancedMesh(o.type==='galaxy'?new T.SphereGeometry(1,64,40):geometry,this.material,count);mesh.frustumCulled=false;const dummy=new T.Object3D();
 for(let i=0;i<count;i++){let p;if(o.type==='galaxy')p=[0,0,0];else if(o.type==='galaxy-cluster'||o.type==='group')p=[normal(),normal(),normal()].map(x=>x*o.r*.28);else if(o.type==='void')p=[normal(),normal(),normal()].map(x=>x*o.r*.25);else{const t=rand(),a=(i%3)*2.094+t*.8,r=o.r*t;p=[r*Math.cos(a)+normal()*o.r*.045,r*Math.sin(a)*.7+normal()*o.r*.045,(normal()*.04+.12*Math.sin(t*5+i%3))*o.r];}
 // Broad illustrative populations are cut out of the named void, not placed uniformly through it.
 const b=this.byId.get('bootes-void'),world=p.map((x,j)=>x+o.p[j]);if(o.type!=='void'&&o.type!=='galaxy'&&Math.hypot(...world.map((x,j)=>x-b.p[j]))<b.r*.92){dummy.scale.setScalar(0);}else{const r=o.type==='galaxy'?o.r:(o.type==='group'?.002+.015*rand():.015+.045*rand());dummy.scale.set(r,r*(.65+.35*rand()),r*(o.id==='m87'?.65:.09+.1*rand()));}dummy.position.set(...world);dummy.rotation.set(rand()*Math.PI,rand()*Math.PI,rand()*Math.PI);if(o.type==='galaxy')dummy.rotation.set(.45,0,o.id==='m31'?.5:-.4);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);mesh.setColorAt(i,o.id==='m87'?new T.Color(1.2,.87,.66):new T.Color().setHSL(.09+rand()*.08,.3,.7+rand()*.2));}
 mesh.instanceMatrix.needsUpdate=true;this.galaxies.add(mesh);
 const outline=new T.Group();for(let a=0;a<3;a++){const points=[];for(let j=0;j<=160;j++){const t=j*Math.PI/80,v=[Math.cos(t)*o.r,Math.sin(t)*o.r,0];if(a===1)[v[1],v[2]]=[v[2],v[1]];if(a===2)[v[0],v[2]]=[v[2],v[0]];points.push(new T.Vector3(...v));}outline.add(new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:colors[o.type],transparent:true,opacity:.25})));}outline.position.set(...o.p);this.envelopes.add(outline);
 const pick=new T.Mesh(new T.SphereGeometry(o.r,24,16),new T.MeshBasicMaterial({visible:false}));pick.position.set(...o.p);pick.userData.data=o;this.root.add(pick);this.targets.push(pick);this.entries.push({o,mesh,outline,pick});
 }
 // These links express schematic density connections, never measured filament centre lines.
 const edges=[['local-group','virgo-cluster'],['virgo-cluster','centaurus'],['centaurus','norma'],['norma','shapley'],['coma','hercules-cluster'],['perseus','perseus-pisces']];
 for(const [a,b]of edges){const A=new T.Vector3(...this.byId.get(a).p),B=new T.Vector3(...this.byId.get(b).p),mid=A.clone().lerp(B,.5).add(new T.Vector3(0,A.distanceTo(B)*.09,0));const curve=new T.CatmullRomCurve3([A,mid,B]);const tube=new T.Mesh(new T.TubeGeometry(curve,64,Math.max(.08,A.distanceTo(B)*.003),8,false),new T.MeshBasicMaterial({color:0x72b4d8,transparent:true,opacity:.38,depthWrite:false}));this.filaments.add(tube);}
 this.sun=new T.Mesh(new T.SphereGeometry(.08,32,20),new T.MeshBasicMaterial({color:0x94ebd0}));this.root.add(this.sun);
 }
 update(level,selected,span,{envelopes=true,filaments=true,boost=6}={}){this.material.uniforms.boost.value=boost;this.material.uniforms.minPixel.value=boost>1?1.8:0;this.envelopes.visible=envelopes;this.filaments.visible=filaments&&level>0;this.sun.scale.setScalar(Math.max(.5,span*.003));for(const e of this.entries){const active=e.o.level<=level||e.o.id===selected;const near=span<e.o.r*.4;const broad=['basin','supercluster','attractor'].includes(e.o.type);e.mesh.visible=active&&(!broad||span>e.o.r*.25);e.outline.visible=active&&!near&&e.o.type!=='galaxy'&&(e.o.id===selected||e.o.type==='void'||e.o.type==='basin');for(const line of e.outline.children)line.material.opacity=e.o.id===selected?.55:.18;e.pick.visible=active;}}
}
