// Distances rounded for orientation; extents are expressly illustrative envelopes.
// Coordinates are equatorial J2000, shared with the cockpit. Units: million light-years.
export const MLY=1e6;
export const xyz=(ra,dec,d)=>{const a=ra*Math.PI/180,b=dec*Math.PI/180;return [d*Math.cos(b)*Math.cos(a),d*Math.cos(b)*Math.sin(a),d*Math.sin(b)];};
const nasa='https://imagine.gsfc.nasa.gov/features/cosmic/nearest_superclusters_info.html';
const large='https://science.nasa.gov/universe/galaxies/large-scale-structures/';
const simbad=id=>'https://simbad.cds.unistra.fr/simbad/sim-id?Ident='+encodeURIComponent(id);
const rows=[
{id:'local-group',name:'Groupe local',type:'group',ra:10.7,dec:41.3,d:.8,r:3,level:0,inside:['virgo-supercluster','laniakea'],contains:['milky-way','m31','m33'],summary:'Notre petit ensemble de galaxies. La Voie lactée et Andromède en sont les deux grandes composantes.',relation:'Nous sommes ici. Le Groupe local ne fait pas partie de l’amas de la Vierge.',extent:'Enveloppe illustrative de 6 millions d’al',links:[['NASA · groupes et amas',large]]},
{id:'milky-way',name:'Voie lactée',type:'galaxy',ra:266.4168,dec:-29.0078,d:.027,r:.055,level:0,inside:['local-group'],summary:'Notre galaxie. Le Soleil se trouve dans son disque, à environ 27 000 al du centre.',relation:'Une galaxie, à l’intérieur du Groupe local.',links:[['NASA · galaxies','https://science.nasa.gov/universe/galaxies/']]},
{id:'m31',name:'Andromède · M31',type:'galaxy',ra:10.68471,dec:41.26875,d:2.5,r:.11,level:0,inside:['local-group'],summary:'Grande galaxie spirale voisine de la Voie lactée.',relation:'Membre du Groupe local ; elle n’est pas l’étape suivante de la hiérarchie.',links:[['NASA · Andromède','https://www.nasa.gov/universe/galaxies/andromeda-galaxy/']]},
{id:'m33',name:'Triangle · M33',type:'galaxy',ra:23.46207,dec:30.66018,d:3,r:.03,level:0,inside:['local-group'],summary:'Galaxie spirale du Groupe local, plus petite qu’Andromède.',relation:'Autre membre de notre groupe.',links:[['NASA · M33','https://www.nasa.gov/image-article/triangulum-galaxy/']]},
{id:'virgo-cluster',name:'Amas de la Vierge',type:'galaxy-cluster',ra:187.706,dec:12.391,d:54,r:6,level:1,inside:['virgo-supercluster','laniakea'],contains:['m87'],summary:'Une concentration de nombreuses galaxies, dominée notamment par M87. Un amas de galaxies est bien plus grand qu’un amas d’étoiles.',relation:'Notre voisin, pas notre contenant : le Groupe local est en dehors de cet amas.',links:[['NASA · distance de la Vierge','https://science.nasa.gov/asset/hubble/dss-annotated-image-of-the-virgo-cluster/'],['CDS · direction de M87',simbad('M87')]]},
{id:'m87',name:'M87',type:'galaxy',ra:187.706,dec:12.391,d:54,r:.12,level:1,inside:['virgo-cluster'],summary:'Galaxie elliptique géante de la Vierge, avec un trou noir central célèbre. Sa forme représentée ici est une reconstitution.',relation:'Une galaxie au cœur de l’amas de la Vierge.',links:[['NASA · M87','https://science.nasa.gov/mission/hubble/science/explore-the-night-sky/hubble-messier-catalog/messier-87/']]},
{id:'virgo-supercluster',name:'Superamas de la Vierge',type:'supercluster',ra:187.706,dec:12.391,d:54,r:60,level:1,inside:['laniakea'],contains:['local-group','virgo-cluster'],summary:'Le « superamas local » historique : une région comprenant notre Groupe local et l’amas de la Vierge. Ce n’est pas un gigantesque amas compact.',relation:'Premier grand ensemble qui nous englobe dans cette lecture. La Vierge donne son nom à deux structures différentes.',extent:'Enveloppe schématique de 120 millions d’al ; pas une frontière mesurée',links:[['NASA · superamas proches',nasa]]},
{id:'centaurus',name:'Amas du Centaure',type:'galaxy-cluster',ra:192.2,dec:-41.3,d:170,r:7,level:2,inside:['laniakea'],summary:'Amas Abell 3526, l’une des concentrations du voisinage Hydra–Centaure.',relation:'Une autre concentration de galaxies dans la région de Laniakea.',links:[['NASA · Centaure',nasa],['CDS · Abell 3526',simbad('Abell 3526')]]},
{id:'norma',name:'Amas de Norma',type:'galaxy-cluster',ra:243,dec:-60.9,d:220,r:7,level:2,inside:['great-attractor','laniakea'],summary:'Abell 3627 : un amas massif partiellement caché derrière le plan de la Voie lactée.',relation:'Un repère observé dans la région du Grand Attracteur.',links:[['NASA · Norma et Grand Attracteur','https://science.nasa.gov/missions/hubble/hubble-focuses-on-the-great-attractor/'],['CDS · Abell 3627',simbad('Abell 3627')]]},
{id:'great-attractor',name:'Grand Attracteur',type:'attractor',ra:243,dec:-60.9,d:220,r:40,level:2,inside:['laniakea'],contains:['norma'],summary:'Une région de surdensité associée aux mouvements de galaxies. Ce n’est ni une étoile, ni un objet compact, ni un trou noir qui avale les galaxies.',relation:'Dans Laniakea. Le repère est placé vers Norma ; la région n’a pas de centre ni de contour uniques précisément établis.',extent:'Zone de repérage illustrative ; distance représentative de Norma',links:[['NASA · Grand Attracteur','https://science.nasa.gov/missions/hubble/hubble-focuses-on-the-great-attractor/'],['Tully et al. · Laniakea','https://www.nature.com/articles/nature13674']]},
{id:'laniakea',name:'Laniakea',type:'basin',ra:243,dec:-60.9,d:180,r:250,level:2,contains:['virgo-supercluster','great-attractor','centaurus'],summary:'Un bassin d’attraction défini à partir des mouvements particuliers des galaxies, après séparation de l’expansion générale. Environ 500 millions d’al d’étendue.',relation:'Notre environnement à grande échelle selon la définition de 2014. Ce bassin n’est pas un ensemble entièrement lié qui restera assemblé pour toujours.',extent:'Enveloppe illustrative de 500 millions d’al ; ne reproduit pas la frontière Cosmicflows',links:[['Tully et al. 2014 · définition','https://www.nature.com/articles/nature13674'],['NASA · échelle de Laniakea','https://science.nasa.gov/image-article/apod-2014-september-10-laniakea-our-home-supercluster-of-galaxies/']]},
{id:'perseus',name:'Amas de Persée',type:'galaxy-cluster',ra:49.95,dec:41.51,d:240,r:7,level:2,inside:['perseus-pisces'],summary:'Abell 426, une concentration majeure de galaxies et de gaz chaud.',relation:'Dans une autre structure, Persée–Poissons, à côté de notre environnement.',links:[['NASA · Persée–Poissons',nasa],['CDS · Abell 426',simbad('Abell 426')]]},
{id:'perseus-pisces',name:'Persée–Poissons',type:'supercluster',ra:30,dec:30,d:220,r:150,level:2,contains:['perseus'],summary:'Un long ensemble de concentrations de galaxies, de l’ordre de 300 millions d’al d’étendue.',relation:'Voisin de Laniakea, pas une couche qui l’entoure. Orientation et forme du volume simplifiées.',links:[['NASA · Persée–Poissons',nasa]]},
{id:'coma',name:'Amas de Coma',type:'galaxy-cluster',ra:194.95,dec:27.98,d:305,r:8,level:3,inside:['coma-supercluster'],summary:'Abell 1656 : un amas riche de la Chevelure de Bérénice.',relation:'Avec l’amas du Lion, il domine le superamas de Coma.',links:[['NASA · Coma',nasa],['CDS · Abell 1656',simbad('Abell 1656')]]},
{id:'coma-supercluster',name:'Superamas de Coma',type:'supercluster',ra:185,dec:25,d:300,r:70,level:3,contains:['coma'],summary:'Région dominée par les amas de Coma et du Lion, appartenant au paysage de murs et de filaments proches.',relation:'Une structure voisine ; elle ne contient pas Laniakea.',extent:'Volume schématique de repérage',links:[['NASA · Coma',nasa]]},
{id:'hercules-cluster',name:'Amas d’Hercule',type:'galaxy-cluster',ra:241.28,dec:17.75,d:500,r:7,level:3,inside:['hercules-supercluster'],summary:'Abell 2151, un amas riche en galaxies spirales et en interactions.',relation:'À distinguer du superamas d’Hercule et de l’amas globulaire M13, qui est dans notre propre galaxie.',links:[['NASA · Hercule','https://apod.nasa.gov/apod/ap201107.html'],['CDS · Abell 2151',simbad('Abell 2151')]]},
{id:'hercules-supercluster',name:'Superamas d’Hercule',type:'supercluster',ra:241,dec:17,d:500,r:50,level:3,contains:['hercules-cluster'],summary:'Ensemble comprenant notamment les amas Abell 2147, 2151 et 2152.',relation:'Voisin du côté proche du grand vide du Bouvier. Aucune relation avec une succession obligatoire de destinations.',extent:'Volume schématique de repérage',links:[['Étude des amas d’Hercule','https://ntrs.nasa.gov/search.jsp?R=19800036108']]},
{id:'shapley',name:'Concentration de Shapley',type:'supercluster',ra:202.5,dec:-31,d:650,r:80,level:3,summary:'Une concentration très massive de galaxies et d’amas, à environ 650 millions d’al.',relation:'Au-delà de la région du Grand Attracteur dans cette direction ; elle contribue au champ gravitationnel à grande échelle.',extent:'Volume schématique autour de la concentration centrale',links:[['MPE · eROSITA et Shapley','https://www.mpe.mpg.de/7461761/news20200619?c=260760']]},
{id:'bootes-void',name:'Vide du Bouvier',type:'void',ra:222.5,dec:46,d:700,r:160,level:3,summary:'Une immense région beaucoup moins riche en galaxies que la moyenne. Elle contient tout de même des galaxies : « vide » ne veut pas dire absence totale de matière.',relation:'Une sous-densité dans la toile cosmique, pas un objet qui nous englobe et pas un trou noir.',extent:'Diamètre de repérage ≈320 millions d’al ; limites et distances dépendent de la définition et de la cosmologie',links:[['Kirshner et al. 1987 · relevé original','https://articles.adsabs.harvard.edu/pdf/1987ApJ...314..493K'],['Relevé HI dans le vide','https://arxiv.org/abs/astro-ph/9511127']]}
];
export const STRUCTURES=rows.map(o=>({...o,p:xyz(o.ra,o.dec,o.d),inside:o.inside||[],contains:o.contains||[],extent:o.extent||'Taille du volume de représentation, pas une limite physique nette'}));
export const LEVELS=[
{id:'group',name:'Groupe local',span:8,focus:'local-group',text:'Des galaxies réunies dans notre groupe. La Vierge est encore beaucoup plus loin.'},
{id:'virgo',name:'Voisinage de la Vierge',span:150,focus:'virgo-supercluster',text:'Notre groupe et l’amas de la Vierge : deux ensembles distincts dans le superamas local historique.'},
{id:'laniakea',name:'Laniakea et voisins',span:650,focus:'laniakea',text:'Bassin d’attraction de Laniakea, région du Grand Attracteur et voisinage Persée–Poissons.'},
{id:'web',name:'Superamas et grands vides',span:1800,focus:'bootes-void',text:'Hercule, Coma, Shapley et le vide du Bouvier : des directions différentes dans la toile cosmique.'}
];
export const TYPE_NAMES={galaxy:'Galaxie',group:'Groupe de galaxies','galaxy-cluster':'Amas de galaxies',supercluster:'Superamas',basin:'Bassin d’attraction',attractor:'Région de surdensité',void:'Vide cosmique'};
export function cosmicObjects(){return STRUCTURES.filter(o=>!['m31','m33','milky-way'].includes(o.id)).map(o=>({...o,id:'cosmic:'+o.id,type:'cosmic',cosmicType:o.type,kind:TYPE_NAMES[o.type],xyz:o.p.map(x=>x*MLY),d:o.d*MLY,radiusLy:o.r*MLY,guide:false,aliases:[o.name.replace('d’Hercule','Hercule')],planets:[],note:o.summary+' '+o.relation+' '+o.extent+'. Carte et galaxies internes illustratives ; expansion cosmologique non simulée.',links:o.links}));}
