import {mapPoints} from './map-points.js';
import * as T from 'three';
import {norm,sub} from './physics.js';
// Representative Local Group members, not an exhaustive galaxy catalogue.
const rows=[
 ['m31','Andromède · M31',10.68471,41.26875,2500000,110000,77,38,0,'https://www.nasa.gov/universe/galaxies/andromeda-galaxy/'],
 ['m33','Triangle · M33',23.46207,30.66018,3000000,30000,54,23,0,'https://www.nasa.gov/image-article/triangulum-galaxy/'],
 ['lmc','Grand Nuage de Magellan',80.89417,-69.75611,163000,16000,35,120,1,'https://www.nasa.gov/universe/nasas-swift-produces-best-ultraviolet-maps-of-the-nearest-galaxies/'],
 ['smc','Petit Nuage de Magellan',13.15833,-72.80028,200000,10000,45,30,1,'https://www.nasa.gov/universe/galaxies/magellanic-clouds/']
];
export function localGroupObjects(){return rows.map(([id,name,ra,dec,d,radiusLy,inc,pa,irregular,source])=>{const a=ra*Math.PI/180,b=dec*Math.PI/180;return {id,name,type:'galaxy',kind:irregular?'Galaxie irrégulière · Groupe local':'Galaxie spirale · Groupe local',xyz:[d*Math.cos(b)*Math.cos(a),d*Math.cos(b)*Math.sin(a),d*Math.sin(b)],d,radiusLy,inc,pa,irregular,guide:true,aliases:[id.toUpperCase(),id==='m31'?'Andromeda':''],planets:[],motionStatus:'Centre conservé ; pas de dynamique du Groupe local',note:'Direction centrale SIMBAD et distance de référence NASA arrondie. Volume, taille du domaine lumineux, bras, profondeur et orientation du rendu sont des reconstructions approximatives. Aucun catalogue stellaire interne résolu ni mouvement d’ensemble prédictif.',links:[['NASA · distance et contexte',source],['SIMBAD · coordonnées','https://simbad.cds.unistra.fr/simbad/sim-id?Ident='+id.toUpperCase()]]};});}
export function galaxyOrientation(o){const forward=new T.Vector3(...o.xyz).normalize(),north=new T.Vector3(0,0,1);north.addScaledVector(forward,-north.dot(forward)).normalize();const east=new T.Vector3().crossVectors(north,forward).normalize(),pa=o.pa*Math.PI/180;const major=north.clone().multiplyScalar(Math.cos(pa)).addScaledVector(east,Math.sin(pa));const normal=forward.clone().applyAxisAngle(major,o.inc*Math.PI/180);const minor=new T.Vector3().crossVectors(normal,major).normalize();return new T.Matrix3().set(major.x,major.y,major.z,minor.x,minor.y,minor.z,normal.x,normal.y,normal.z);}
export const localGroupGLSL=`uniform vec3 groupCenters[4];uniform mat3 groupRotations[4];uniform float groupShapes[4];uniform float groupTime;
vec3 groupRadiance(vec3 ray){vec3 total=vec3(0);for(int j=0;j<4;j++){vec3 eye=groupRotations[j]*(-groupCenters[j]),dir=groupRotations[j]*ray;float b=dot(eye,dir),disc=b*b-dot(eye,eye)+1.;if(disc<0.)continue;float lo=max(0.,-b-sqrt(disc)),hi=-b+sqrt(disc);if(hi<=lo)continue;float ds=(hi-lo)/64.;vec3 light=vec3(0);float trans=1.;for(int i=0;i<64;i++){vec3 p=eye+dir*(lo+(float(i)+.5)*ds);float r=length(p.xy),theta=atan(p.y,p.x)-groupTime;float arms=pow(.5+.5*cos(2.*theta-8.*log(max(r,.025))),5.);float disk=exp(-r*3.5)*exp(-abs(p.z)/.045)*(1.-smoothstep(.78,1.,r));float bulge=exp(-length(p/vec3(.17,.17,.11))*2.);float rough=.65+.35*sin(p.x*43.+sin(p.y*25.))*sin(p.y*37.+p.z*21.);if(groupShapes[j]>.5){arms=rough;disk*=.8+.5*sin(p.y*18.);bulge*=.15;}float dust=disk*(.4+arms)*rough;trans*=exp(-dust*ds*6.);light+=(disk*(.25+arms)*mix(vec3(.32,.49,.8),vec3(.8,.62,.4),rough*.5)+bulge*vec3(1.,.72,.4))*ds*trans*6.;}total+=light;}return total;}`;
export class LocalGroupLayer{
 constructor(uniforms,objects,mapWorld,makeLabel,mapScene){this.objects=objects.filter(o=>o.type==='galaxy');this.u=uniforms;Object.assign(uniforms,{groupCenters:{value:this.objects.map(()=>new T.Vector3())},groupRotations:{value:this.objects.map(galaxyOrientation)},groupShapes:{value:this.objects.map(o=>o.irregular)},groupTime:{value:0}});this.labels=[];this.pickables=[];
 let seed=7291;const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
 for(const o of this.objects){const inv=galaxyOrientation(o).clone().transpose(),p=[],c=[];for(let k=0;k<7000;k++){const r=Math.pow(rnd(),1.7),a=(k%2)*Math.PI+4*Math.log(Math.max(r,.01))+(rnd()-.5)*.7;const v=new T.Vector3(r*Math.cos(a),r*Math.sin(a),(rnd()-.5)*.055).applyMatrix3(inv).multiplyScalar(o.radiusLy).add(new T.Vector3(...o.xyz));p.push(...v.toArray());c.push(.65+r*.1,.55+r*.2,.38+r*.55);}const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute(p,3));geometry.setAttribute('color',new T.Float32BufferAttribute(c,3));mapWorld.add(new T.Points(geometry,mapPoints(2,.6)));
 const marker=new T.Mesh(new T.SphereGeometry(o.radiusLy*.4,12,8),new T.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}));marker.position.set(...o.xyz);marker.userData.object=o;mapWorld.add(marker);this.pickables.push(marker);
 const label=makeLabel(o.name,'#e9c48e');mapScene.add(label);this.labels.push({label,o});}
 }
 update(s,k,map){this.objects.forEach((o,i)=>this.u.groupCenters.value[i].set(...sub(o.xyz,s.pos)).divideScalar(o.radiusLy));this.u.groupTime.value=s.t*2*Math.PI/250000000;for(const {label,o}of this.labels){label.position.set(...o.xyz.map(x=>x*k));label.position.x+=2;label.visible=map&&k<.0001;}}
}
