import * as T from 'three';
import {gammaU,norm,unit,mul,sub} from './physics.js';
import {CloseupModel,closeupGLSL} from './closeup.js';
import {localGroupGLSL} from './local-group.js';
import {blackHoleGLSL} from './black-hole.js';
import {accretionOf,MODEL_CODE,diskAxis} from './compact-objects.js';
import {radiusLy,hash} from './body-data.js';
import {schwarzschildR} from './gravity-field.js'; // positions are isotropic coordinates; optics uses Schwarzschild r
import {cloudGLSL} from './environments.js';
// Every incoming sky ray (including extended objects) shares this observer boost.
// RGB radiance is a spectral proxy, not a measured spectrum: see physics-v2.html.
export class SkyOptics{
 constructor(lut,objects=[]){const size=typeof innerWidth!=='undefined'&&innerWidth<620?512:1024;this.target=new T.WebGLCubeRenderTarget(size,{type:T.HalfFloatType,minFilter:T.LinearFilter,magFilter:T.LinearFilter,generateMipmaps:false});this.cube=new T.CubeCamera(.001,2500,this.target);this.backdropTarget=new T.WebGLCubeRenderTarget(256,{type:T.HalfFloatType,minFilter:T.LinearFilter,generateMipmaps:false});this.backdropCamera=new T.CubeCamera(.001,2500,this.backdropTarget);this.backdrop=new T.Mesh(new T.SphereGeometry(1900,16,12),new T.ShaderMaterial({uniforms:{sky:{value:this.backdropTarget.texture}},vertexShader:'varying vec3 ray;void main(){ray=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 ray;uniform samplerCube sky;void main(){gl_FragColor=vec4(textureCube(sky,normalize(ray)).rgb,1.);}',side:T.BackSide,depthWrite:false,depthTest:false}));this.backdrop.renderOrder=-30;this.scene=new T.Scene();this.camera=new T.OrthographicCamera(-1,1,1,-1,0,1);const tex=new T.DataTexture(new Float32Array(lut),512,1,T.RGBAFormat,T.FloatType);tex.minFilter=tex.magFilter=T.LinearFilter;tex.needsUpdate=true;
 this.material=new T.ShaderMaterial({depthTest:false,depthWrite:false,uniforms:{sky:{value:this.target.texture},lut:{value:tex},rotation:{value:new T.Matrix3()},axis:{value:new T.Vector3(0,0,-1)},g:{value:1},momentum:{value:0},optics:{value:0},shift:{value:1},exposure:{value:1},aspect:{value:1},tanFov:{value:.7},band:{value:1},cloudActive:{value:0},cloudCenter:{value:new T.Vector3()},cloudRotation:{value:new T.Matrix3()},shape:{value:0},seed:{value:0},bhActive:{value:0},radial:{value:new T.Vector3()},diskNormal:{value:new T.Vector3(.18,.84,.51).normalize()},observerRadius:{value:15},diskModel:{value:0},diskTmax:{value:1e4},diskOuter:{value:30},disk:{value:0},time:{value:0}},vertexShader:'varying vec2 uvp;void main(){uvp=position.xy;gl_Position=vec4(position.xy,0.,1.);}',fragmentShader:`precision highp float;varying vec2 uvp;uniform samplerCube sky;uniform sampler2D lut;uniform mat3 rotation;uniform vec3 axis;uniform float g,momentum,optics,shift,exposure,aspect,tanFov,band;
${closeupGLSL}
${blackHoleGLSL}
${cloudGLSL}
${localGroupGLSL}
uniform float bhActive;
vec4 thermal(float t){float clipped=clamp(t,100.,1000000.);vec4 c=texture2D(lut,vec2(log(clipped/100.)/log(10000.),.5));c.a+=log(max(t,100.)/clipped);return c;}
void main(){vec3 n=normalize(rotation*vec3(uvp.x*aspect*tanFov,uvp.y*tanFov,-1.));vec3 ray=n;float D=1.;if(optics>.5&&momentum>.000001){float mu=clamp(dot(n,axis),-1.,1.);vec3 perpendicular=n-axis*mu;float oneMinus=mu>0.?dot(perpendicular,perpendicular)/(1.+mu):1.-mu;float inverseD=g*oneMinus+mu/(g+momentum);D=1./max(inverseD,1.e-20);ray=normalize((perpendicular+axis*(1./(g+momentum)-g*oneMinus))*D);}
vec3 L=max(vec3(0),textureCube(sky,ray).rgb)+groupRadiance(ray);
if(bhActive>.5)L=traceBlackHole(ray);
if(cloudActive>.5)L=cloudRadiance(ray,L*.35);
if(bodyKind>.5){L*=band<2.?.035:1.;L=localRadiance(ray,L);}
if(optics>.5&&shift>.5&&momentum>.000001){if(band<2.5){float blue=L.b/(L.r+L.b+1.e-20);float temp=mix(2800.,16000.,clamp((blue-.18)/.66,0.,1.));vec4 rest=thermal(temp),seen=thermal(temp*D);float gain=exp(clamp(seen.a-rest.a,-70.,60.));if(temp*D<100.)gain=0.;L*=gain*seen.rgb/max(rest.rgb,vec3(.0001));}else{L*=exp(clamp(4.*log(D),-70.,60.));}}
L*=exposure;vec3 rgb=1.-exp(-max(L,vec3(0)));if(band==0.){float y=dot(rgb,vec3(.2126,.7152,.0722));rgb=mix(vec3(y),rgb,smoothstep(.15,.8,y));}gl_FragColor=vec4(pow(rgb,vec3(1./2.2)),1.);}`});this.scene.add(new T.Mesh(new T.PlaneGeometry(2,2),this.material));this.closeup=new CloseupModel(this.material.uniforms,objects,lut);}
 capture(renderer,scene,layers){const viewport=new T.Vector4(),scissor=new T.Vector4();renderer.getViewport(viewport);renderer.getScissor(scissor);const test=renderer.getScissorTest(),target=renderer.getRenderTarget();renderer.setScissorTest(false);
 if(layers){const {stars,local,backgrounds}=layers,sharp=Array.isArray(stars)?stars:[stars],sv=sharp.map(o=>o.visible),lv=local.visible,visibility=backgrounds.map(o=>o.visible);sharp.forEach(o=>o.visible=false);local.visible=false;this.backdropCamera.update(renderer,scene);sharp.forEach((o,i)=>o.visible=sv[i]);local.visible=lv;backgrounds.forEach(o=>o.visible=false);scene.add(this.backdrop);this.cube.update(renderer,scene);scene.remove(this.backdrop);backgrounds.forEach((o,i)=>o.visible=visibility[i]);}
 else this.cube.update(renderer,scene);
 renderer.setRenderTarget(target);renderer.setViewport(viewport);renderer.setScissor(scissor);renderer.setScissorTest(test);}

 render(renderer,camera,s,u,enabled){camera.updateMatrixWorld();const bh=s.target?.type==='blackhole'?s.target:null,rr=bh?schwarzschildR(norm(sub(s.pos,bh.lightXYZ||bh.xyz))/radiusLy(bh),.5):Infinity;const bhU=this.material.uniforms;const cloud=s.target&&['nebula','pillars'].includes(s.target.type)&&norm(sub(s.target.xyz,s.pos))/radiusLy(s.target)<120?s.target:null;bhU.cloudActive.value=+!!cloud;if(cloud){bhU.cloudCenter.value.set(...sub(cloud.lightXYZ||cloud.xyz,s.pos)).divideScalar(radiusLy(cloud));const q=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,0,-1),new T.Vector3(...cloud.xyz).normalize());bhU.cloudRotation.value.setFromMatrix4(new T.Matrix4().makeRotationFromQuaternion(q)).transpose();bhU.shape.value=cloud.type==='pillars'?1:['crab','vela-remnant','sgrae'].includes(cloud.id)?2:cloud.id==='eta-car'?3:['ring','helix'].includes(cloud.id)?4:cloud.id==='sgrb2'?5:0;bhU.seed.value=hash(cloud.id)%1000;}bhU.bhActive.value=+(s.lensing&&rr<150&&rr>1.02);if(bh){bhU.radial.value.set(...sub(s.pos,bh.lightXYZ||bh.xyz)).normalize();bhU.observerRadius.value=s.gr?.id===bh.id?s.gr.r:rr;const acc=accretionOf(bh);const earth=this.closeup.objects.find(x=>x.id==='solar:Terre');bhU.diskNormal.value.set(...diskAxis(bh,earth?earth.xyz:[0,0,0]));bhU.diskModel.value=MODEL_CODE[acc.model]||0;bhU.diskTmax.value=acc.Tmax||1e4;bhU.diskOuter.value=acc.rOut||30;bhU.time.value=s.wall;} const x=this.material.uniforms;x.rotation.value.setFromMatrix4(camera.matrixWorld);x.axis.value.set(...unit(u));x.g.value=gammaU(u);x.momentum.value=norm(u);x.optics.value=+enabled;x.shift.value=+s.doppler;x.exposure.value=s.exposure;x.band.value=s.band;x.aspect.value=camera.aspect;x.tanFov.value=Math.tan(camera.fov/2*Math.PI/180);renderer.render(this.scene,this.camera);}
}
