import * as T from 'three';
import {densityGLSL} from './galaxy.js';
export function temperature(o){if(o.temperature>500)return o.temperature;if(o.bp_rp!=null)return Math.max(1800,Math.min(30000,8500/(1+o.bp_rp*.52)));const c=(o.spect||'G').replace(/^(sd|d)/,'')[0];return {O:35000,B:16000,A:8500,F:6500,G:5500,K:4300,M:3100,D:11000}[c]||5500;}
export function createStarlight(stars,lut){const p=[],a=[],t=[];for(const s of stars){p.push(...s.xyz);let magnitude=s.id==='h0'?-26.74:s.mag??10;let distance=s.id==='h0'?1/63241.077:s.d;const mAbs=magnitude-5*Math.log10(Math.max(distance/3.26156,1e-8))+5;a.push(mAbs);t.push(temperature(s));}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(p,3));geo.setAttribute('catalogPosition',new T.Float32BufferAttribute(p,3));geo.setAttribute('absMag',new T.Float32BufferAttribute(a,1));geo.setAttribute('temp',new T.Float32BufferAttribute(t,1));const tex=new T.DataTexture(new Float32Array(lut),512,1,T.RGBAFormat,T.FloatType);tex.minFilter=tex.magFilter=T.LinearFilter;tex.needsUpdate=true;
 const uniforms={ship:{value:new T.Vector3()},speed:{value:new T.Vector3()},optics:{value:1},shift:{value:1},exposure:{value:1},band:{value:1},extinction:{value:1},lut:{value:tex}};
 const vertexShader=`attribute vec3 catalogPosition;attribute float absMag;attribute float temp;uniform vec3 ship,speed;uniform float optics,shift,exposure,band,extinction;uniform sampler2D lut;varying vec3 light;${densityGLSL}
vec4 thermal(float T){return texture2D(lut,vec2(clamp(log(max(100.,T)/100.)/log(10000.),0.,1.),.5));}
void main(){vec3 delta=position;float d=max(length(delta),.00000001);vec3 n=delta/d;float D=1.;if(optics>.5){D=(1.+dot(n,speed))*inversesqrt(1.-dot(speed,speed));n=aberrateDir(n,speed);}vec4 rest=thermal(temp);vec4 col=thermal(temp*(shift>.5?D:1.));float mag=absMag+5.*log(d/3.26156)/log(10.)-5.;float flux=pow(10.,-.4*(mag-3.));if(shift>.5&&optics>.5)flux*=exp(clamp(col.a-rest.a,-60.,60.))/(D*D);float tau=opticalDepth(galCentre(ship),galCentre(catalogPosition))-opticalDepth(galCentre(vec3(0)),galCentre(catalogPosition));flux*=exp(-clamp(tau,-8.,30.)*extinction*(band==2.?.08:1.));if(band>=3.)flux*=.005;flux*=exposure;float size=clamp(1.25+1.1*pow(max(flux,0.),.16),1.25,6.);light=col.rgb*flux/(size*size*.08);if(band==0.){float y=dot(light,vec3(.2126,.7152,.0722));light=mix(vec3(y),light,smoothstep(.3,4.,flux));}gl_Position=projectionMatrix*modelViewMatrix*vec4(n*1000.,1.);gl_PointSize=size;}`;
 const fragmentShader=`varying vec3 light;void main(){float r=length(gl_PointCoord-.5)*2.;if(r>1.)discard;float psf=exp(-12.*r*r)*(1.-smoothstep(.7,1.,r));gl_FragColor=vec4(min(max(light,vec3(0)),vec3(5000))*psf,1.);}`;
 const material=new T.ShaderMaterial({vertexShader,fragmentShader,uniforms,transparent:true,depthWrite:false,blending:T.AdditiveBlending});const points=new T.Points(geo,material);points.frustumCulled=false;points.userData.stars=stars;return points;}
